name: Deploy to Plesk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Node.js, npm, and sass on server
      run: |
        ssh -o StrictHostKeyChecking=no  netto-decor-habitat.p_rto3hj8h1u@185.63.173.106 << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

          command -v nvm || echo 'nvm command not found'
          nvm install 18 || echo 'Failed to install Node.js'
          nvm use 18 || echo 'Failed to use Node.js version 18'

          command -v npm || echo 'npm command not found'
          npm install -g sass || echo 'Failed to install sass'
          command -v sass || echo 'sass command not found'
        EOF
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Debug Info - Environment
      run: |
        echo "Running as $(whoami)"
        echo "Home directory: $HOME"
        ls -al $HOME

    - name: Debug Info - SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no  netto-decor-habitat.p_rto3hj8h1u@185.63.173.106 "echo 'SSH connection established' && ls -al /var/www/vhosts/netto-decor-habitat.pixelea.fr/httpdocs/wp-content/themes/pixelea"

    - name: Sync files to Plesk
      run: |
        rsync -avz --delete --exclude '.git/' ./ netto-decor-habitat.p_rto3hj8h1u@185.63.173.106:/var/www/vhosts/netto-decor-habitat.pixelea.fr/httpdocs/wp-content/themes/pixelea
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Run deploy script on server
      run: |
        ssh -o StrictHostKeyChecking=no netto-decor-habitat.p_rto3hj8h1u@185.63.173.106 << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

          bash /var/www/vhosts/netto-decor-habitat.pixelea.fr/httpdocs/wp-content/themes/netto-decor/.deploy/deploy.sh
        EOF
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
